version: '3.8'
services:
  db:
    image: postgres:15
    container_name: taskify-db
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
