spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=dGFza2lmeS1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LWtleS12ZXJ5LXNlY3VyZS1hbmQtbG9uZw==
jwt.expiration=86400

spring.security.debug=false

logging.level.com.taskifyApplication=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

server.port=8080

spring.application.name=Taskify